### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by Mesks** [xtudbxk/TMP#9]
Hi, thank you for the amazing open source code. When I try to run the test code some error happened, if you are experienced with this, please help me explain it.

1. According to your readme, the test commend is "python3 basicsr/train.py -opt options/test/TMP/test_TMP.yaml", I guess the validation entrance is basicsr/test.py, but I use it got a error.
2. The error is:
              Traceback (most recent call last):
                File "basicsr/test.py", line 49, in <module>
                  test_pipeline(root_path)
                File "basicsr/test.py", line 44, in test_pipeline
                  model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
                File "basicsr/../basicsr/models/base_model.py", line 48, in validation
                  self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
                File "basicsr/../basicsr/models/video_base_model.py", line 136, in nondist_validation
                  self.dist_validation(dataloader, current_iter, tb_logger, save_img)
                File "basicsr/../basicsr/models/video_recurrent_model.py", line 71, in dist_validation
                  gt_cuda, hidden_states = net_g_cuda(inp_cuda, hidden_states, return_hs=True)
                File "/share3/home/queshicheng/dependences/miniconda3/envs/TMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
                  return forward_call(*input, **kwargs)
                File "basicsr/../basicsr/archs/tmp_arch.py", line 67, in forward
                  assert h % 4 == 0 and w % 4 == 0, ('The height and width must be multiple of 4.')
              AssertionError: The height and width must be multiple of 4.
so, is it means the resolution of LQ images must be multiple of 4? Well, the resolution of my image sequence is 1920x1080, is it available?

By the way, I changed the options/test/TMP/test_TMP.yaml, "dataroot_gt" and "dataroot_lq" changed to my dataset (three png sequences, the value is the parent directory of these sequence folders), dataroot_gt is the directory of my 1920x1080 sequences and dataroot_lq is the directory of the original sequence been bicubic downsampled sequences (480x270). And "pretrain_network_g" to points to the pretrained model pth file. I'm not sure it's right.

**Comment by Mesks** [comment]
I can make the program run by commenting out line 66 of basicsr/archs/tmp_arch.py, but the results obtained from multiple runs are different, and there is a floating error in the second decimal place. Is this right? In addition, is there a built-in time statistics program? Which period of time is the running time in Table 1 of the paper statistically calculated? Finally, thank you again for your contribution.

**Comment by xtudbxk** [comment]
Sorry for the late reply; your email was buried under many others.

1. train.py -> test.py. Thanks, you’re right.
2. The option seems correct. The warning is puzzling since your input meets the requirements.
3. I’ve run tests multiple times with stable results. This method relies on motion continuity, which might not be present in your dataset. Increasing iterations could help.
4. We don’t have that code in this repository. Runtime is evaluated by processing five consecutive 180x320 frames on a V100 GPU, averaging ten repetitions.
